Algoritmo "parouimpar"
// Professor : Cintia pinho
// Descrição   : Verifica se o número digitado é par ou ímpar
// Autor(a)    : maria ria
// Data atual  : 02/08/2022
var
numero: inteiro


Inicio
// entrada
escreval("Digite um número")
leia(numero)

//processamento
se (numero mod 2=0)entao
 escreval("O número o numero que voce digitou é par")
senao
  escreval("O número que voce digitou é ímpar")
fimse


Fimalgoritmo