Algoritmo "areadotriangulo"
// Disciplina   : [solicita base e a altura e calcule a area do triangulo]
// Autor(a)    : Maria Rita
// Data atual  : 08/03/2022
Var
base,alt,area:real


Inicio
//entrada
escreval("digite a base do triangulo")
leia(base)
escreval("digite a base do triangulo")
leia(alt)

//processamento
area<- (base*alt)/2

//saida
escreval("a area do triangulo e:",area)


Fimalgoritmo