Algoritmo "exercicio 1"
// Professor   : Cintia
// Descrição   : criar um  algoritmo que leia um vetor de 10 números inteiros. Em seguida, calcular e escrever o somatório dos valores .
// Autor(a)    : Maria Rita
// Data atual  : 01/11/2022
Var
v:vetor[1..10] de inteiro
n1, n2,soma:inteiro


Inicio
para n1:=1 ate 10 faca
     escreval("digite o ",n1," valor desejado")
     leia(n2)
     soma<-soma+n2
fimpara
     escreval("a soma total dos valores é:",soma)


Fimalgoritmo