algoritmo "Qnt"
// Função :pedir a quantidade minima, maxima e estoque medio
// Autor : maria rita
// Data : 10/05/2022
// Seção de Declarações 
var
qntmax,qntmin,estoqmed:real
inicio
// entrada
escreval(" digite a quantidade maxima do estoque")
leia (qntmax)
escreval("digite a quantidade minima do estoque")
leia (qntmin)
//saida
estoqmed<-(qntmin+qntmax)/2
escreval("o estoque medio é",estoqmed)
fimalgoritmo
